apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-openshift-logging
  namespace: argocd
spec:
  destination:
    namespace: openshift-logging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-bootstrap/sealed-secrets
    repoURL: https://github.com/tjungbauer/OCP-Lab-Setup
    targetRevision: master
