
- name: Create OperatorGroup
  k8s:
    state: present
    definition: "{{ lookup('template', '20-operator-group.yaml.j2') }}"

- name: Create Operator Subscription
  k8s:
    state: present
    definition: "{{ lookup('template', '30-subscription.yaml.j2') }}"
